
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: healthcare
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - healthcare_network

  mongodb:
    image: mongo:6
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - healthcare_network

  backend:
    build: .
    container_name: healthcare_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongodb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/healthcare
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_DATA_MONGODB_URI: mongodb://mongo:mongo123@mongodb:27017/healthcare
    networks:
      - healthcare_network

volumes:
  postgres_data:
  mongo_data:

networks:
  healthcare_network:
    driver: bridge
