

# Get all doctors
# Get all doctors with pagination
GET http://localhost:8080/api/admin/doctors?page=0&size=2&sort=lastName,asc
Authorization: Bearer   eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1NzQ4NDMzMCwiZXhwIjoxNzU3NDg3OTMwfQ.zc14tm1tHsGy59rEH6Rr4WCEh1Vff7YKPnECLFbbB4SWjlBId1f9VeeGFI6t9cvT8q6rW9Wv7nFIFHinZCXmsg
Content-Type: application/json

###

# Get doctor by ID
GET http://localhost:8080/api/admin/doctors/1
Content-Type: application/json

###

# Create doctor
POST http://localhost:8080/api/admin/doctors
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "Doctor123!",
  "phone": "123456789",
  "specialty": "Cardiology",
  "yearsOfExperience": 10,
  "slots": []
}

###

# Update doctor
PUT http://localhost:8080/api/admin/doctors/1
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "Doctor123!",
  "phone": "987654321",
  "specialty": "Cardiology",
  "yearsOfExperience": 12,
  "slots": []
}

###

# Delete doctor
DELETE http://localhost:8080/api/admin/doctors/1

###

# Get all patients
GET http://localhost:8080/api/admin/patients?page=0&size=5&sort=firstName,desc
Authorization: Bearer   eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1NzQ4NDMzMCwiZXhwIjoxNzU3NDg3OTMwfQ.zc14tm1tHsGy59rEH6Rr4WCEh1Vff7YKPnECLFbbB4SWjlBId1f9VeeGFI6t9cvT8q6rW9Wv7nFIFHinZCXmsg


###

# Get patient by ID
GET http://localhost:8080/api/admin/patients/6
Content-Type: application/json

###

# Create patient
POST http://localhost:8080/api/admin/patients
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Brown",
  "email": "alice.brown@example.com",
  "password": "Patient123!",
  "phone": "555123456",
  "dateOfBirth": "1990-05-20",
  "medicalHistory": "No known allergies"
}

###

# Update patient
PUT http://localhost:8080/api/admin/patients/6
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Brown",
  "email": "alice.brown@example.com",
  "password": "Patient123!",
  "phone": "555987654",
  "dateOfBirth": "1990-05-20",
  "medicalHistory": "Allergic to penicillin"
}

###

# Delete patient
DELETE http://localhost:8080/api/admin/patients/5

