

# Get all doctors
# Get all doctors with pagination
GET http://localhost:8080/api/admin/doctors?page=0&size=2&sort=lastName,asc
Authorization: Bearer   eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1NzUzMjE1MCwiZXhwIjoxNzU3NTM1NzUwfQ.OtmykzaQgyuX3enRVetToq_WOV5B21II5S80x9ogxR4EYuKDonM5wP0xXNvirDd0Iqktci7CLczquFYsx2rrpQ
Content-Type: application/json

###

# Get doctor by ID
GET http://localhost:8080/api/admin/doctors/31
Authorization: Bearer   eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1NzUzMjE1MCwiZXhwIjoxNzU3NTM1NzUwfQ.OtmykzaQgyuX3enRVetToq_WOV5B21II5S80x9ogxR4EYuKDonM5wP0xXNvirDd0Iqktci7CLczquFYsx2rrpQ
Content-Type: application/json

###

# Create doctor
POST http://localhost:8080/api/admin/doctors
Authorization: Bearer   eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1NzUzMjE1MCwiZXhwIjoxNzU3NTM1NzUwfQ.OtmykzaQgyuX3enRVetToq_WOV5B21II5S80x9ogxR4EYuKDonM5wP0xXNvirDd0Iqktci7CLczquFYsx2rrpQ
Content-Type: application/json

{
  "firstName": "francis",
  "lastName": "miadi",
  "email": "jfm@example.com",
  "password": "Doctor123!",
  "phone": "123456789",
  "specialty": "Cardiology",
  "yearsOfExperience": 10,
  "slots": []
}

###

# Update doctor
PUT http://localhost:8080/api/admin/doctors/42
Authorization: Bearer   eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1NzUzMjE1MCwiZXhwIjoxNzU3NTM1NzUwfQ.OtmykzaQgyuX3enRVetToq_WOV5B21II5S80x9ogxR4EYuKDonM5wP0xXNvirDd0Iqktci7CLczquFYsx2rrpQ
Content-Type: application/json

{
  "firstName": "francis",
  "lastName": "miadiii",
  "email": "jfm@example.com",
  "password": "Doctor123!",
  "phone": "987654321",
  "specialty": "Cardiology",
  "yearsOfExperience": 12,
  "slots": []
}

###

# Delete doctor
DELETE http://localhost:8080/api/admin/doctors/42
Authorization: Bearer   eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1NzUzMjE1MCwiZXhwIjoxNzU3NTM1NzUwfQ.OtmykzaQgyuX3enRVetToq_WOV5B21II5S80x9ogxR4EYuKDonM5wP0xXNvirDd0Iqktci7CLczquFYsx2rrpQ


###

# Get all patients
GET http://localhost:8080/api/admin/patients?page=0&size=5&sort=firstName,desc
Authorization: Bearer   eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTgwMjEwNTYsImV4cCI6MTc1ODAyNDY1Nn0.Nvza2zA_MoRC3SeoEARBXz6czXk37ZwgyI5YDGowXi1e7C9T0lG-G91S3IPa9pxhNF08lS-00hcxTnmpnTMgHA


###

# Get patient by ID
GET http://localhost:8080/api/admin/patients/36
Authorization: Bearer   eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1NzUzMjE1MCwiZXhwIjoxNzU3NTM1NzUwfQ.OtmykzaQgyuX3enRVetToq_WOV5B21II5S80x9ogxR4EYuKDonM5wP0xXNvirDd0Iqktci7CLczquFYsx2rrpQ
Content-Type: application/json

###

# Create patient
POST http://localhost:8080/api/admin/patients
Authorization: Bearer   eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1NzUzMjE1MCwiZXhwIjoxNzU3NTM1NzUwfQ.OtmykzaQgyuX3enRVetToq_WOV5B21II5S80x9ogxR4EYuKDonM5wP0xXNvirDd0Iqktci7CLczquFYsx2rrpQ
Content-Type: application/json

{
  "firstName": "z",
  "lastName": "z",
  "email": "zzzz@example.com",
  "password": "Patient123!",
  "phone": "555123456",
  "dateOfBirth": "1990-05-20",
  "medicalHistory": "No known allergies"
}

###

# Update patient
PUT http://localhost:8080/api/admin/patients/43
Authorization: Bearer   eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1NzUzMjE1MCwiZXhwIjoxNzU3NTM1NzUwfQ.OtmykzaQgyuX3enRVetToq_WOV5B21II5S80x9ogxR4EYuKDonM5wP0xXNvirDd0Iqktci7CLczquFYsx2rrpQ
Content-Type: application/json

{
  "firstName": "zzzzzzz",
  "lastName": "z",
  "email": "zzzz@example.com",
  "password": "Patient123!",
  "phone": "555123456",
  "dateOfBirth": "1990-05-20",
  "medicalHistory": "No known allergies"
}

###

# Delete patient
DELETE http://localhost:8080/api/admin/patients/43
Authorization: Bearer   eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1NzUzMjE1MCwiZXhwIjoxNzU3NTM1NzUwfQ.OtmykzaQgyuX3enRVetToq_WOV5B21II5S80x9ogxR4EYuKDonM5wP0xXNvirDd0Iqktci7CLczquFYsx2rrpQ


