

# Get all appointments for a doctor
GET http://localhost:8080/api/doctor/31/appointments?page=0&size=5
Authorization: Bearer   eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhbXIuemVkYW5AZXhhbXBsZS5jb20iLCJyb2xlIjoiRE9DVE9SIiwiaWF0IjoxNzU3NTMzMDczLCJleHAiOjE3NTc1MzY2NzN9.t2F09g8Hsc6coK6IkjPT1hvVL-14u0OKHw8TG__pbLs6d_fsgFqS_KgFPIwoxNXiZBmejRvXSFKrHJBkP0k7Ag
###

# Get appointment by ID
GET http://localhost:8080/api/doctor/31/appointments/6+
Authorization: Bearer   eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhbXIuemVkYW5AZXhhbXBsZS5jb20iLCJyb2xlIjoiRE9DVE9SIiwiaWF0IjoxNzU3NTMzMDczLCJleHAiOjE3NTc1MzY2NzN9.t2F09g8Hsc6coK6IkjPT1hvVL-14u0OKHw8TG__pbLs6d_fsgFqS_KgFPIwoxNXiZBmejRvXSFKrHJBkP0k7Ag


###

# Mark appointment as completed
PUT http://localhost:8080/api/doctor/4/appointments/1/complete

###

# Add prescription
POST http://localhost:8080/api/doctor/31/prescriptions
Content-Type: application/json
Authorization: Bearer   eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhbXIuemVkYW5AZXhhbXBsZS5jb20iLCJyb2xlIjoiRE9DVE9SIiwiaWF0IjoxNzU3NTMzMDczLCJleHAiOjE3NTc1MzY2NzN9.t2F09g8Hsc6coK6IkjPT1hvVL-14u0OKHw8TG__pbLs6d_fsgFqS_KgFPIwoxNXiZBmejRvXSFKrHJBkP0k7Ag

{
  "patientId": 36,
  "doctorId": 31,
  "appointmentId": 6,
  "medicines": ["kareeeeeeeeeeeeem", "Ibuprofen 200mg"],
  "notes": "Take medicines after meals"
}

###

# Get all prescriptions for a doctor
GET http://localhost:8080/api/doctor/31/prescriptions?page=0&size=5&sort=date,desc
Authorization: Bearer   eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhbXIuemVkYW5AZXhhbXBsZS5jb20iLCJyb2xlIjoiRE9DVE9SIiwiaWF0IjoxNzU3NTMzMDczLCJleHAiOjE3NTc1MzY2NzN9.t2F09g8Hsc6coK6IkjPT1hvVL-14u0OKHw8TG__pbLs6d_fsgFqS_KgFPIwoxNXiZBmejRvXSFKrHJBkP0k7Ag


###

# Get prescriptions for a patient
GET http://localhost:8080/api/doctor/9/prescriptions/patient/11?page=0&size=5&sort=date,desc
Authorization: Bearer   eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb2huLmRvZTJAZXhhbXBsZS5jb20iLCJyb2xlIjoiRE9DVE9SIiwiaWF0IjoxNzU3NDg2MDc5LCJleHAiOjE3NTc0ODk2Nzl9.8dF2Nl4aGRx_G7DfTfQiQrHb10RvDQeIe_gKYTp3KEEBmPmMVYeiW9W6BIxwVhvnm0bDGJa9zrGxKBXDXneD-Q

###

# Create slot
POST http://localhost:8080/api/doctor/31/slots
Authorization: Bearer   eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhbXIuemVkYW5AZXhhbXBsZS5jb20iLCJyb2xlIjoiRE9DVE9SIiwiaWF0IjoxNzU3NTMzMDczLCJleHAiOjE3NTc1MzY2NzN9.t2F09g8Hsc6coK6IkjPT1hvVL-14u0OKHw8TG__pbLs6d_fsgFqS_KgFPIwoxNXiZBmejRvXSFKrHJBkP0k7Ag
Content-Type: application/json

{
  "startTime": "2025-09-13T10:00:00",
  "endTime": "2025-09-13T11:30:00",
  "available": true
}

###

# Get all slots for a doctor
GET http://localhost:8080/api/doctor/31/slots?page=0&size=5&sort=startTime,asc
Authorization: Bearer   eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhbXIuemVkYW5AZXhhbXBsZS5jb20iLCJyb2xlIjoiRE9DVE9SIiwiaWF0IjoxNzU3NTMzMDczLCJleHAiOjE3NTc1MzY2NzN9.t2F09g8Hsc6coK6IkjPT1hvVL-14u0OKHw8TG__pbLs6d_fsgFqS_KgFPIwoxNXiZBmejRvXSFKrHJBkP0k7Ag

###

# Update slot
PUT http://localhost:8080/api/doctor/1/slots/1
Content-Type: application/json

{
  "startTime": "2025-09-07T09:15:00",
  "endTime": "2025-09-07T09:45:00",
  "available": true
}

###

# Delete slot
DELETE http://localhost:8080/api/doctor/1/slots/1
