

# View profile
GET http://localhost:8080/api/patient/11
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrYXJlZW1hbHF1dG9iMjAwM0BnbWFpbC5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc1NzQwNTU3OSwiZXhwIjoxNzU3NDA5MTc5fQ.AkoIO4QBFKktGBhW1SqrYwzlwtGVK_uacK6IRyXtkK_M6_e07ftyv-GE88ooMtPG-YmK2L6Y0Ce2GcdhDXic6g


###

# Update profile
PUT http://localhost:8080/api/patient/6
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Brown",
  "email": "alice.brown@example.com",
  "password": "Patient123!",
  "phone": "555987654",
  "dateOfBirth": "1990-05-26",
  "medicalHistory": "Allergic to penicillin"
}

###

# Get doctors by specialty
GET http://localhost:8080/api/patient/doctors?specialty=Cardiology
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrYXJlZW1hbHF1dG9iMjAwM0BnbWFpbC5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc1NzQwNTU3OSwiZXhwIjoxNzU3NDA5MTc5fQ.AkoIO4QBFKktGBhW1SqrYwzlwtGVK_uacK6IRyXtkK_M6_e07ftyv-GE88ooMtPG-YmK2L6Y0Ce2GcdhDXic6g

###

# Get available slots for a doctor
GET http://localhost:8080/api/patient/doctors/9/slots
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrYXJlZW1hbHF1dG9iMjAwM0BnbWFpbC5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc1NzQxNzYzNywiZXhwIjoxNzU3NDIxMjM3fQ.X5BBaW6JDBU7Cdz2khCtE3BqoxiCxC4lFuMpOa05Z9Acp2SvhDBfSkZaL9Xm5Tatjk8sD6TlX7Heiht-Oz0lbQ

###

# Book appointment
POST http://localhost:8080/api/patient/11/appointments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrYXJlZW1hbHF1dG9iMjAwM0BnbWFpbC5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc1NzQxNzYzNywiZXhwIjoxNzU3NDIxMjM3fQ.X5BBaW6JDBU7Cdz2khCtE3BqoxiCxC4lFuMpOa05Z9Acp2SvhDBfSkZaL9Xm5Tatjk8sD6TlX7Heiht-Oz0lbQ

{
  "slotId": 4,
  "patientId": 11
}

###

# Get all appointments for a patient
GET http://localhost:8080/api/patient/11/appointments
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrYXJlZW1hbHF1dG9iMjAwM0BnbWFpbC5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc1NzQwNTU3OSwiZXhwIjoxNzU3NDA5MTc5fQ.AkoIO4QBFKktGBhW1SqrYwzlwtGVK_uacK6IRyXtkK_M6_e07ftyv-GE88ooMtPG-YmK2L6Y0Ce2GcdhDXic6g

###

# Cancel appointment
DELETE http://localhost:8080/api/patient/11/appointments/4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrYXJlZW1hbHF1dG9iMjAwM0BnbWFpbC5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc1NzQxNzYzNywiZXhwIjoxNzU3NDIxMjM3fQ.X5BBaW6JDBU7Cdz2khCtE3BqoxiCxC4lFuMpOa05Z9Acp2SvhDBfSkZaL9Xm5Tatjk8sD6TlX7Heiht-Oz0lbQ

###

# Get prescriptions for a patient
GET http://localhost:8080/api/patient/11/prescriptions
Authorization: Bearer yJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrYXJlZW1hbHF1dG9iMjAwM0BnbWFpbC5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc1NzQwNTM4NywiZXhwIjoxNzU3NDA4OTg3fQ.Z9uQLpDx_njUk2nxfAbpHmH73TAXRpLid6CcZIJQH56hwP9P52RhXFWVNwe6zRrS61fWCqZmiW_nC_UznhV1hQ


###

# Get medical record
GET http://localhost:8080/api/patient/6/medical-record
