

# View profile
GET http://localhost:8080/api/patient/37
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmcmFuay50YXlsb3JAZXhhbXBsZS5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc1NzUzNDIyNywiZXhwIjoxNzU3NTM3ODI3fQ.BebIVZ9d2EdQsBWUcc36axNB-_jkuanYqYFVpxkhMjoK9AZG-IdB8RfTmsn6w6n6tTsLRz3ZZvdXCMSBK3rrgQ


###

# Update profile
PUT http://localhost:8080/api/patient/37
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmcmFuay50YXlsb3JAZXhhbXBsZS5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc1NzUzNDIyNywiZXhwIjoxNzU3NTM3ODI3fQ.BebIVZ9d2EdQsBWUcc36axNB-_jkuanYqYFVpxkhMjoK9AZG-IdB8RfTmsn6w6n6tTsLRz3ZZvdXCMSBK3rrgQ
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Brown",
  "email": "m.h@example.com",
  "password": "Patient123!",
  "phone": "555987654",
  "dateOfBirth": "1990-05-26",
  "medicalHistory": "Allergic to penicillin"
}

###

# Get doctors by specialty
GET http://localhost:8080/api/patient/doctors?specialty=Cardiology&page=0&size=5&sort=yearsOfExperience,desc
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtLmhAZXhhbXBsZS5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc1NzUzNDM1OCwiZXhwIjoxNzU3NTM3OTU4fQ.-hRyH8Wd9gYe1ZCAl3M8L0LkbvE7LDLEIzSw8YkyhMhrZDHtEKrAK7WDl3s6XitvuUyCWOjSh_KX9p816u95kw

###

# Get available slots for a doctor
GET http://localhost:8080/api/patient/doctors/31/slots?page=0&size=5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtLmhAZXhhbXBsZS5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc1NzUzNDM1OCwiZXhwIjoxNzU3NTM3OTU4fQ.-hRyH8Wd9gYe1ZCAl3M8L0LkbvE7LDLEIzSw8YkyhMhrZDHtEKrAK7WDl3s6XitvuUyCWOjSh_KX9p816u95kw

###

# Book appointment
POST http://localhost:8080/api/patient/37/appointments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtLmhAZXhhbXBsZS5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc1NzUzNDM1OCwiZXhwIjoxNzU3NTM3OTU4fQ.-hRyH8Wd9gYe1ZCAl3M8L0LkbvE7LDLEIzSw8YkyhMhrZDHtEKrAK7WDl3s6XitvuUyCWOjSh_KX9p816u95kw

{
  "slotId": 11,
  "patientId": 37
}

###

# Get all appointments for a patient
GET http://localhost:8080/api/patient/37/appointments?page=0&size=1&sort=slot.startTime,desc
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtLmhAZXhhbXBsZS5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc1NzUzNDM1OCwiZXhwIjoxNzU3NTM3OTU4fQ.-hRyH8Wd9gYe1ZCAl3M8L0LkbvE7LDLEIzSw8YkyhMhrZDHtEKrAK7WDl3s6XitvuUyCWOjSh_KX9p816u95kw

###

# Cancel appointment
DELETE http://localhost:8080/api/patient/37/appointments/7
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtLmhAZXhhbXBsZS5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc1NzUzNDM1OCwiZXhwIjoxNzU3NTM3OTU4fQ.-hRyH8Wd9gYe1ZCAl3M8L0LkbvE7LDLEIzSw8YkyhMhrZDHtEKrAK7WDl3s6XitvuUyCWOjSh_KX9p816u95kw

###

# Get prescriptions for a patient
GET http://localhost:8080/api/patient/11/prescriptions?page=0&size=5&sort=date,desc
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrYXJlZW1hbHF1dG9iMjAwM0BnbWFpbC5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc1NzQ4NDUzOSwiZXhwIjoxNzU3NDg4MTM5fQ.q5e1j7hLgexTyeXdRrAY-TUZl0EONY2SCyO1pyrw8Ov7c5wpe_zs39DUp7khxHlsBsIP6iau9CsBGHvDk6dh_w


###

# Get medical record
GET http://localhost:8080/api/patient/37/medical-record
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtLmhAZXhhbXBsZS5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc1NzUzNDM1OCwiZXhwIjoxNzU3NTM3OTU4fQ.-hRyH8Wd9gYe1ZCAl3M8L0LkbvE7LDLEIzSw8YkyhMhrZDHtEKrAK7WDl3s6XitvuUyCWOjSh_KX9p816u95kw
