

# View profile
GET http://localhost:8080/api/patient/11
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrYXJlZW1hbHF1dG9iMjAwM0BnbWFpbC5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc1NzQwNTU3OSwiZXhwIjoxNzU3NDA5MTc5fQ.AkoIO4QBFKktGBhW1SqrYwzlwtGVK_uacK6IRyXtkK_M6_e07ftyv-GE88ooMtPG-YmK2L6Y0Ce2GcdhDXic6g


###

# Update profile
PUT http://localhost:8080/api/patient/6
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Brown",
  "email": "alice.brown@example.com",
  "password": "Patient123!",
  "phone": "555987654",
  "dateOfBirth": "1990-05-26",
  "medicalHistory": "Allergic to penicillin"
}

###

# Get doctors by specialty
GET http://localhost:8080/api/patient/doctors?specialty=Cardiology&page=0&size=5&sort=yearsOfExperience,desc
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrYXJlZW1hbHF1dG9iMjAwM0BnbWFpbC5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc1NzQ4NDUzOSwiZXhwIjoxNzU3NDg4MTM5fQ.q5e1j7hLgexTyeXdRrAY-TUZl0EONY2SCyO1pyrw8Ov7c5wpe_zs39DUp7khxHlsBsIP6iau9CsBGHvDk6dh_w

###

# Get available slots for a doctor
GET http://localhost:8080/api/patient/doctors/11/slots?page=0&size=5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrYXJlZW1hbHF1dG9iMjAwM0BnbWFpbC5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc1NzQ4NDUzOSwiZXhwIjoxNzU3NDg4MTM5fQ.q5e1j7hLgexTyeXdRrAY-TUZl0EONY2SCyO1pyrw8Ov7c5wpe_zs39DUp7khxHlsBsIP6iau9CsBGHvDk6dh_w

###

# Book appointment
POST http://localhost:8080/api/patient/11/appointments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrYXJlZW1hbHF1dG9iMjAwM0BnbWFpbC5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc1NzQxNzYzNywiZXhwIjoxNzU3NDIxMjM3fQ.X5BBaW6JDBU7Cdz2khCtE3BqoxiCxC4lFuMpOa05Z9Acp2SvhDBfSkZaL9Xm5Tatjk8sD6TlX7Heiht-Oz0lbQ

{
  "slotId": 4,
  "patientId": 11
}

###

# Get all appointments for a patient
GET http://localhost:8080/api/patient/11/appointments?page=0&size=1&sort=slot.startTime,desc
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrYXJlZW1hbHF1dG9iMjAwM0BnbWFpbC5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc1NzQ4NDUzOSwiZXhwIjoxNzU3NDg4MTM5fQ.q5e1j7hLgexTyeXdRrAY-TUZl0EONY2SCyO1pyrw8Ov7c5wpe_zs39DUp7khxHlsBsIP6iau9CsBGHvDk6dh_w

###

# Cancel appointment
DELETE http://localhost:8080/api/patient/11/appointments/4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrYXJlZW1hbHF1dG9iMjAwM0BnbWFpbC5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc1NzQxNzYzNywiZXhwIjoxNzU3NDIxMjM3fQ.X5BBaW6JDBU7Cdz2khCtE3BqoxiCxC4lFuMpOa05Z9Acp2SvhDBfSkZaL9Xm5Tatjk8sD6TlX7Heiht-Oz0lbQ

###

# Get prescriptions for a patient
GET http://localhost:8080/api/patient/11/prescriptions?page=0&size=5&sort=date,desc
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrYXJlZW1hbHF1dG9iMjAwM0BnbWFpbC5jb20iLCJyb2xlIjoiUEFUSUVOVCIsImlhdCI6MTc1NzQ4NDUzOSwiZXhwIjoxNzU3NDg4MTM5fQ.q5e1j7hLgexTyeXdRrAY-TUZl0EONY2SCyO1pyrw8Ov7c5wpe_zs39DUp7khxHlsBsIP6iau9CsBGHvDk6dh_w


###

# Get medical record
GET http://localhost:8080/api/patient/6/medical-record
