### Patient Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "kareem.qutob2@example.com",
  "password": "Patient123!"
}

### Search for doctors by specialty
GET http://localhost:8080/api/patient/doctors?specialty=Cardiology&page=0&size=5&sort=yearsOfExperience,desc
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrYXJlZW0ucXV0b2IyQGV4YW1wbGUuY29tIiwicm9sZSI6IlBBVElFTlQiLCJpYXQiOjE3NTc1MjI0NjQsImV4cCI6MTc1NzUyNjA2NH0.1pbGpL60g6NGRZOr-GzfgbIqlcQV5cIGxhxPCtjH1MBlBwqToJH4WUTbDZcy3EFmWdO8GN77VyN0SxDwBhJjyw

### Get available slots for selected doctor
GET http://localhost:8080/api/patient/doctors/31/slots?page=0&size=5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrYXJlZW0ucXV0b2IyQGV4YW1wbGUuY29tIiwicm9sZSI6IlBBVElFTlQiLCJpYXQiOjE3NTc1MjI0NjQsImV4cCI6MTc1NzUyNjA2NH0.1pbGpL60g6NGRZOr-GzfgbIqlcQV5cIGxhxPCtjH1MBlBwqToJH4WUTbDZcy3EFmWdO8GN77VyN0SxDwBhJjyw

### Book appointment
POST http://localhost:8080/api/patient/36/appointments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrYXJlZW0ucXV0b2IyQGV4YW1wbGUuY29tIiwicm9sZSI6IlBBVElFTlQiLCJpYXQiOjE3NTc1MjI0NjQsImV4cCI6MTc1NzUyNjA2NH0.1pbGpL60g6NGRZOr-GzfgbIqlcQV5cIGxhxPCtjH1MBlBwqToJH4WUTbDZcy3EFmWdO8GN77VyN0SxDwBhJjyw

{
  "slotId": 13,
  "patientId": 35
}

### Verify booked appointments
GET http://localhost:8080/api/patient/35/appointments?page=0&size=5&sort=slot.startTime,desc
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrYXJlZW0ucXV0b2IyQGV4YW1wbGUuY29tIiwicm9sZSI6IlBBVElFTlQiLCJpYXQiOjE3NTc1MjI0NjQsImV4cCI6MTc1NzUyNjA2NH0.1pbGpL60g6NGRZOr-GzfgbIqlcQV5cIGxhxPCtjH1MBlBwqToJH4WUTbDZcy3EFmWdO8GN77VyN0SxDwBhJjyw
