### Admin Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Admin123!"
}

### Add a new doctor
POST http://localhost:8080/api/auth/register/doctor
Content-Type: application/json
Authorization: Bearer {{ADMIN_TOKEN}}

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "Doctor123!",
  "phone": "123456789",
  "specialty": "Cardiology",
  "yearsOfExperience": 10,
  "slots": []
}

### Get all doctors
GET http://localhost:8080/api/admin/doctors?page=0&size=5&sort=lastName,asc
Authorization: Bearer {{ADMIN_TOKEN}}

### Get doctor by ID
GET http://localhost:8080/api/admin/doctors/{{DOCTOR_ID}}
Authorization: Bearer {{ADMIN_TOKEN}}

### Update doctor info
PUT http://localhost:8080/api/admin/doctors/{{DOCTOR_ID}}
Content-Type: application/json
Authorization: Bearer {{ADMIN_TOKEN}}

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "Doctor123!",
  "phone": "987654321",
  "specialty": "Cardiology",
  "yearsOfExperience": 12,
  "slots": []
}

### Delete doctor
DELETE http://localhost:8080/api/admin/doctors/{{DOCTOR_ID}}
Authorization: Bearer {{ADMIN_TOKEN}}
